"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()   # Загрузка .env файла

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-x6qm*f9!m=ydyav=l3w=7ye#=(-wb@ux$3!i2gi1f))8$-85pa"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.postgres',
    "api",
    "website",
    "sellship",


]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASE_NAME = os.getenv('DATABASE_NAME')      # Берем их из .env файла
DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD')
DATABASE_HOST = os.getenv('DATABASE_HOST')
DATABASE_PORT = os.getenv('DATABASE_PORT')

DATABASE_COUNT = int(os.getenv('DATABASE_COUNT', '1'))

def read_db_config_by_index(index: int):
    """Читает конфиг БД из переменных окружения с индексами.
    Для index == 1 сохраняем обратную совместимость: берём без индекса как fallback.
    Поддерживаем переменные: DATABASE_ENGINE_i, DATABASE_NAME_i, DATABASE_USER_i,
    DATABASE_PASSWORD_i, DATABASE_HOST_i, DATABASE_PORT_i.
    """
    def get_env_indexed(key: str, fallback: str | None = None):
        value = os.getenv(f"DATABASE_{key}_{index}")
        if value is not None:
            return value
        # fallback только для первого индекса — берём неиндексированные значения
        if index == 1:
            return os.getenv(f"DATABASE_{key}", fallback)
        return fallback

    return {
        'ENGINE': get_env_indexed('ENGINE', 'django.db.backends.postgresql'),
        'NAME': get_env_indexed('NAME', DATABASE_NAME if index == 1 else None),
        'USER': get_env_indexed('USER', DATABASE_USER if index == 1 else None),
        'PASSWORD': get_env_indexed('PASSWORD', DATABASE_PASSWORD if index == 1 else None),
        'HOST': get_env_indexed('HOST', DATABASE_HOST if index == 1 else None),
        'PORT': get_env_indexed('PORT', DATABASE_PORT if index == 1 else None),
    }

DATABASES = {}
for i in range(1, max(1, DATABASE_COUNT) + 1):
    config = read_db_config_by_index(i)
    if i == 1:
        alias = 'default'
    else:
        # Имя алиаса берём из имени БД, если задано, иначе fallback к db{index}
        alias = (config.get('NAME') or f'db{i}')
    DATABASES[alias] = config


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru-RU"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# DB routers
DATABASE_ROUTERS = [
    'core.db_routers.SellshipRouter',
]
