# Generated by Django 5.2.4 on 2025-09-08 10:34

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import sellship.models.item
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFDW',
            fields=[
                ('id', models.CharField(db_column='smart', max_length=15, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='наименование', max_length=100, verbose_name='Наименование')),
                ('originality', models.CharField(db_column='оригинальность', max_length=7, verbose_name='Оригинальность')),
                ('brand', models.JSONField(db_column='бренд', default=list, verbose_name='Бренд')),
                ('connect_brand', models.JSONField(db_column='коннект_бренд', default=list, verbose_name='Коннект бренд')),
                ('transport_type', models.JSONField(db_column='тип_транспорта', default=list, verbose_name='Тип транспорта')),
                ('area_usage', models.JSONField(db_column='область_применения', default=list, verbose_name='Область применения')),
                ('weight', models.FloatField(blank=True, db_column='вес', default=0, verbose_name='Вес')),
                ('volume', models.FloatField(blank=True, db_column='объем', default=0, verbose_name='Объем')),
                ('article', models.JSONField(db_column='артикул', default=list, verbose_name='Артикул')),
                ('connect_article', models.JSONField(db_column='коннект_артикул', default=list, verbose_name='Коннект артикул')),
            ],
            options={
                'verbose_name': 'Запчасть (FDW)',
                'verbose_name_plural': 'Запчасти (FDW)',
                'db_table': '"default_fdw"."smart"',
                'managed': False,
            },
        ),
        # migrations.CreateModel(
        #     name='Item',
        #     fields=[
        #         ('id', models.CharField(db_column='smart', max_length=15, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(blank=True, db_column='наименование', max_length=100, verbose_name='Наименование')),
        #         ('originality', models.CharField(choices=[('OEM', 'OEM'), ('NOT OEM', 'NOT OEM')], db_column='оригинальность', max_length=7, verbose_name='Оригинальность')),
        #         ('brand', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('YAMAHA', 'YAMAHA'), ('QUICKSILVER', 'QUICKSILVER'), ('MERCRUISER', 'MERCRUISER'), ('MERCURY', 'MERCURY')], max_length=15), db_column='бренд', default=list, size=10, verbose_name='Бренд')),
        #         ('connect_brand', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('YAMAHA', 'YAMAHA'), ('QUICKSILVER', 'QUICKSILVER'), ('MERCRUISER', 'MERCRUISER'), ('MERCURY', 'MERCURY')], max_length=15), blank=True, db_column='коннект_бренд', default=list, size=10, verbose_name='Коннект бренд')),
        #         ('transport_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('КАТЕР', 'КАТЕР'), ('АВТО', 'АВТО'), ('СНЕГОХОД', 'СНЕГОХОД')], max_length=15), db_column='тип_транспорта', default=list, size=6, verbose_name='Тип транспорта')),
        #         ('area_usage', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, db_column='область_применения', default=list, size=5, verbose_name='Область применения')),
        #         ('weight', models.FloatField(blank=True, db_column='вес', default=0, verbose_name='Вес')),
        #         ('volume', models.FloatField(blank=True, db_column='объем', default=0, verbose_name='Объем')),
        #         ('article', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), db_column='артикул', default=list, size=None, validators=[sellship.models.item.validate_article_format], verbose_name='Артикул')),
        #         ('connect_article', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, db_column='коннект_артикул', default=list, size=None, validators=[sellship.models.item.validate_article_format], verbose_name='Коннект артикул')),
        #     ],
        #     options={
        #         'verbose_name': 'Запчасть',
        #         'verbose_name_plural': 'Запчасти',
        #         'db_table': 'smart',
        #     },
        # ),
        migrations.CreateModel(
            name='EbayShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_announcement', models.BigIntegerField(db_column='номер_объявления', validators=[django.core.validators.MinValueValidator(100000000000), django.core.validators.MaxValueValidator(999999999999)], verbose_name='Номер объявления')),
                ('max_price', models.IntegerField(blank=True, db_column='максимальная_цена', default=0, null=True, verbose_name='Максимальная цена')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], db_column='приоритет', default='low', verbose_name='Приоритет')),
                ('account_ebay', models.CharField(choices=[('kensinerjack', 'kensinerjack'), ('prom', 'prom')], db_column='аккаунт_ебей', default='kensinerjack', verbose_name='Аккаунт eBay')),
                ('status', models.CharField(choices=[('ЗАКРЫТО', 'ЗАКРЫТО'), ('ЗАВЕРШЕНО', 'ЗАВЕРШЕНО'), ('КУПЛЕННО', 'КУПЛЕННО'), ('ОФФЕР', 'ОФФЕР'), ('НАПИСАЛИ', 'НАПИСАЛИ'), ('СОБРАННО', 'СОБРАННО'), ('ОШИБКИ', 'ОШИБКИ')], db_column='статус', default='КУПЛЕННО', max_length=9, verbose_name='Статус')),
                ('last_updated_status', models.DateTimeField(blank=True, db_column='последнее_обновление_статуса', default=django.utils.timezone.now, null=True, verbose_name='Последнее обновление статуса')),
                ('seller_name', models.CharField(blank=True, db_column='имя_продавца', max_length=100, null=True, verbose_name='Имя продавца')),
                ('shipping_type', models.CharField(choices=[('АВИА', 'АВИА'), ('МОРЕМ', 'МОРЕМ')], db_column='тип_доставки', default='АВИА', max_length=5, verbose_name='Тип доставки')),
                ('final_price', models.FloatField(db_column='финальная_цена', default=0, verbose_name='Финальная цена')),
                ('overhead', models.FloatField(db_column='дополнительные_затраты', default=0, verbose_name='Дополнительные затраты')),
                ('shipper', models.CharField(choices=[('ЕВГЕНИЙ_ДЕЛАВЕР', 'ЕВГЕНИЙ ДЕЛАВЕР'), ('КИРГИЗИЯ_ДЕЛАВЕР', 'КИРГИЗИЯ ДЕЛАВЕР')], db_column='отправщик', default='ЕВГЕНИЙ_ДЕЛАВЕР', max_length=100, verbose_name='Отправщик')),
                ('track_number', models.CharField(blank=True, db_column='трек', max_length=150, null=True, verbose_name='Трек-номер')),
                ('date_arrive', models.DateField(blank=True, db_column='дата_прихода_на_склад', null=True, verbose_name='Дата прихода на склад')),
                ('country', models.CharField(choices=[('США', 'США'), ('ГЕРАМНИЯ', 'ГЕРАМНИЯ')], db_column='страна_склада', default='США', max_length=100, verbose_name='Страна склада')),
                ('comments', models.TextField(db_column='коментарий', verbose_name='Комментарий')),
                ('order_link', models.URLField(blank=True, db_column='ссылка_заказ', max_length=256, null=True, verbose_name='Ссылка на заказ')),
                ('rf_send', models.BooleanField(db_column='рф_отправленно', verbose_name='Отправлено в РФ')),
                ('date_list_create', models.DateField(blank=True, null=True, verbose_name='Дата создания листа')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EURO', 'EURO')], db_column='валюта', default='USD', max_length=10, verbose_name='Валюта')),
                ('smart', models.ForeignKey(db_column='smart', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='sellship.itemfdw', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Информация о доставке eBay',
                'verbose_name_plural': 'Информация о доставке eBay',
            },
        ),
    ]
