# Generated by Django 5.2.4 on 2025-07-15 11:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_column="smart",
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="наименование", max_length=100)),
                (
                    "originality",
                    models.CharField(
                        choices=[("OEM", "OEM"), ("NOT OEM", "NOT OEM")],
                        db_column="оригинальность",
                        max_length=7,
                    ),
                ),
                (
                    "brand",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("YAMAHA", "YAMAHA"),
                                ("QUICKSILVER", "QUICKSILVER"),
                                ("MERCRUISER", "MERCRUISER"),
                                ("MERCURY", "MERCURY"),
                            ]
                        ),
                        db_column="бренд",
                        default=list,
                        size=10,
                    ),
                ),
                (
                    "connect_brand",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("YAMAHA", "YAMAHA"),
                                ("QUICKSILVER", "QUICKSILVER"),
                                ("MERCRUISER", "MERCRUISER"),
                                ("MERCURY", "MERCURY"),
                            ]
                        ),
                        db_column="коннект_бренд",
                        default=list,
                        size=10,
                    ),
                ),
                (
                    "transport_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[("КАТЕР", "КАТЕР"), ("АВТО", "АВТО")]
                        ),
                        db_column="тип_транспорта",
                        default=list,
                        size=6,
                    ),
                ),
                (
                    "area_usage",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        db_column="область_применения",
                        default=list,
                        size=5,
                    ),
                ),
                ("weight", models.FloatField(db_column="вес", default=0)),
                ("volume", models.FloatField(db_column="объем", default=0)),
                (
                    "article",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        db_column="артикул",
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "connect_article",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        db_column="коннект_артикул",
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "smart",
            },
        ),
    ]
