# Generated by Django 5.2.4 on 2025-07-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellship", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Проверка, что в массиве article минимум 1 элемент
                """
                ALTER TABLE smart
                    ADD CONSTRAINT article_not_empty CHECK (array_length(артикул, 1) > 0);
                """,
                """
                ALTER TABLE smart
                    ADD CONSTRAINT connect_article_not_empty CHECK (array_length(коннект_артикул, 1) > 0);
                """,
                # Проверка, что в массиве brand минимум 1 элемент
                """
                ALTER TABLE smart
                    ADD CONSTRAINT brand_not_empty CHECK (array_length(бренд, 1) > 0);
                """,

                """
                ALTER TABLE smart
                    ADD CONSTRAINT connect_brand_not_empty CHECK (array_length(коннект_бренд, 1) > 0);
                """
            ],
            reverse_sql=[
                "ALTER TABLE smart DROP CONSTRAINT IF EXISTS article_not_empty;",
                "ALTER TABLE smart DROP CONSTRAINT IF EXISTS connect_article_not_empty;",
                "ALTER TABLE smart DROP CONSTRAINT IF EXISTS brand_not_empty;",
                "ALTER TABLE smart DROP CONSTRAINT IF EXISTS connect_brand_not_empty;"
            ],
        )
    ]
