# Generated by Django 5.2.4 on 2025-07-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellship", "0002_auto_20250715_1135"),
    ]

    operations = [
        migrations.RunSQL(
            sql = [
            "ALTER TABLE smart DROP CONSTRAINT IF EXISTS article_not_empty;",
            "ALTER TABLE smart DROP CONSTRAINT IF EXISTS connect_article_not_empty;",
            "ALTER TABLE smart DROP CONSTRAINT IF EXISTS brand_not_empty;",
            "ALTER TABLE smart DROP CONSTRAINT IF EXISTS connect_brand_not_empty;"
            ]
        )
    ]
