# Generated by Django 5.2.4 on 2025-07-15 11:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellship", "0003_auto_20250715_1155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="brand",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("YAMAHA", "YAMAHA"),
                        ("QUICKSILVER", "QUICKSILVER"),
                        ("MERCRUISER", "MERCRUISER"),
                        ("MERCURY", "MERCURY"),
                    ],
                    max_length=15,
                ),
                db_column="бренд",
                default=list,
                size=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="connect_brand",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("YAMAHA", "YAMAHA"),
                        ("QUICKSILVER", "QUICKSILVER"),
                        ("MERCRUISER", "MERCRUISER"),
                        ("MERCURY", "MERCURY"),
                    ],
                    max_length=15,
                ),
                db_column="коннект_бренд",
                default=list,
                size=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="transport_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("КАТЕР", "КАТЕР"), ("АВТО", "АВТО")], max_length=15
                ),
                db_column="тип_транспорта",
                default=list,
                size=6,
            ),
        ),
    ]
