# Generated by Django 5.2.4 on 2025-09-08 10:59

import django.contrib.postgres.fields
import sellship.models.item
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellship', '0003_item_alter_ebayshippinginfo_smart'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Item',
        #     fields=[
        #         ('id', models.CharField(db_column='smart', max_length=15, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(blank=True, db_column='наименование', max_length=100, verbose_name='Наименование')),
        #         ('originality', models.CharField(choices=[('OEM', 'OEM'), ('NOT OEM', 'NOT OEM')], db_column='оригинальность', max_length=7, verbose_name='Оригинальность')),
        #         ('brand', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('YAMAHA', 'YAMAHA'), ('QUICKSILVER', 'QUICKSILVER'), ('MERCRUISER', 'MERCRUISER'), ('MERCURY', 'MERCURY')], max_length=15), db_column='бренд', default=list, size=10, verbose_name='Бренд')),
        #         ('connect_brand', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('YAMAHA', 'YAMAHA'), ('QUICKSILVER', 'QUICKSILVER'), ('MERCRUISER', 'MERCRUISER'), ('MERCURY', 'MERCURY')], max_length=15), blank=True, db_column='коннект_бренд', default=list, size=10, verbose_name='Коннект бренд')),
        #         ('transport_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('КАТЕР', 'КАТЕР'), ('АВТО', 'АВТО'), ('СНЕГОХОД', 'СНЕГОХОД')], max_length=15), db_column='тип_транспорта', default=list, size=6, verbose_name='Тип транспорта')),
        #         ('area_usage', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, db_column='область_применения', default=list, size=5, verbose_name='Область применения')),
        #         ('weight', models.FloatField(blank=True, db_column='вес', default=0, verbose_name='Вес')),
        #         ('volume', models.FloatField(blank=True, db_column='объем', default=0, verbose_name='Объем')),
        #         ('article', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), db_column='артикул', default=list, size=None, validators=[sellship.models.item.validate_article_format], verbose_name='Артикул')),
        #         ('connect_article', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, db_column='коннект_артикул', default=list, size=None, validators=[sellship.models.item.validate_article_format], verbose_name='Коннект артикул')),
        #     ],
        #     options={
        #         'verbose_name': 'Запчасть',
        #         'verbose_name_plural': 'Запчасти',
        #         'db_table': 'smart',
        #     },
        # ),
        migrations.AlterModelTable(
            name='itemfdw',
            table='default_fdw.smart',
        ),
    ]
