# Generated by Django 5.2.4 on 2025-07-15 12:18

from django.db import migrations

from sellship.models import TransportType


def create_transport_type_constraint(apps, schema_editor):
    allowed_values = [choice.value for choice in TransportType]
    values_sql = ', '.join(f"'{v}'" for v in allowed_values)
    sql = f'"тип_транспорта" <@ ARRAY[{values_sql}]::varchar[]'

    schema_editor.execute(f"""
        ALTER TABLE smart
        ADD CONSTRAINT transport_type_allowed_values CHECK ({sql});
    """)


def drop_transport_type_constraint(apps, schema_editor):
    schema_editor.execute("""
        ALTER TABLE smart
        DROP CONSTRAINT IF EXISTS transport_type_allowed_values;
    """)

class Migration(migrations.Migration):

    dependencies = [
        ("sellship", "0005_auto_20250715_1157"),
    ]

    operations = [
        migrations.RunPython(create_transport_type_constraint, drop_transport_type_constraint),
    ]
