# Generated by Django 5.2.4 on 2025-07-15 12:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellship", "0006_auto_20250715_1218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="transport_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("КАТЕР", "КАТЕР"),
                        ("АВТО", "АВТО"),
                        ("СНЕГОХОД", "СНЕГОХОД"),
                    ],
                    max_length=15,
                ),
                db_column="тип_транспорта",
                default=list,
                size=6,
            ),
        ),
    ]
