# Generated by Django 5.2.4 on 2025-07-15 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellship", "0007_alter_item_transport_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="area_usage",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                db_column="область_применения",
                default=list,
                size=5,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="connect_article",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                db_column="коннект_артикул",
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="connect_brand",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("YAMAHA", "YAMAHA"),
                        ("QUICKSILVER", "QUICKSILVER"),
                        ("MERCRUISER", "MERCRUISER"),
                        ("MERCURY", "MERCURY"),
                    ],
                    max_length=15,
                ),
                blank=True,
                db_column="коннект_бренд",
                default=list,
                size=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                blank=True, db_column="наименование", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="volume",
            field=models.FloatField(blank=True, db_column="объем", default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="weight",
            field=models.FloatField(blank=True, db_column="вес", default=0),
        ),
    ]
