# Generated by Django 5.2.4 on 2025-07-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellship", "0009_auto_20250715_1235"),
    ]



    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE smart DROP CONSTRAINT IF EXISTS transport_type_allowed_values;",
            ]
        )]
