# Generated by Django 5.2.4 on 2025-07-31 19:23

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import sellship.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellship", "0010_auto_20250715_1239"),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("link", models.URLField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="article",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                db_column="артикул",
                default=list,
                size=None,
                validators=[sellship.models.validate_article_format],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="connect_article",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                db_column="коннект_артикул",
                default=list,
                size=None,
                validators=[sellship.models.validate_article_format],
            ),
        ),
        migrations.CreateModel(
            name="EbayShippingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_announcement",
                    models.BigIntegerField(
                        db_column="номер_объявления",
                        validators=[
                            django.core.validators.MinValueValidator(100000000000),
                            django.core.validators.MaxValueValidator(999999999999),
                        ],
                    ),
                ),
                (
                    "max_price",
                    models.IntegerField(blank=True, db_column="максимальная_цена"),
                ),
                (
                    "account_ebay",
                    models.CharField(
                        choices=[("kensinerjack", "kensinerjack"), ("prom", "prom")],
                        db_column="аккаунт_ебей",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ЗАКРЫТО", "КАТЕР"),
                            ("ЗАВЕРШЕНО", "АВТО"),
                            ("КУПЛЕННО", "СНЕГОХОД"),
                            ("ОФФЕР", "ОФФЕР"),
                            ("НАПИСАЛИ", "НАПИСАЛИ"),
                            ("СОБРАННО", "СОБРАННО"),
                            ("ОШИБКИ", "ОШИБКИ"),
                        ],
                        db_column="статус",
                        max_length=9,
                    ),
                ),
                (
                    "last_updated_status",
                    models.DateTimeField(
                        db_column="последнее_обновление_статуса",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "seller_name",
                    models.CharField(db_column="имя_продавца", max_length=100),
                ),
                (
                    "shipping_type",
                    models.CharField(
                        choices=[("АВИА", "АВИА"), ("МОРЕМ", "МОРЕМ")],
                        db_column="тип_доставки",
                        max_length=5,
                    ),
                ),
                ("final_price", models.FloatField(db_column="финальная_цена")),
                (
                    "overhead",
                    models.FloatField(db_column="дополнительные_затраты", default=0),
                ),
                (
                    "shipper",
                    models.CharField(
                        choices=[
                            ("ЕВГЕНИЙ_ДЕЛАВЕР", "ЕВГЕНИЙ_ДЕЛАВЕР"),
                            ("КИРГИЗИЯ_ДЕЛАВЕР", "КИРГИЗИЯ_ДЕЛАВЕР"),
                        ],
                        db_column="отправщик",
                        max_length=100,
                    ),
                ),
                (
                    "track_number",
                    models.CharField(
                        blank=True, db_column="трек", max_length=150, null=True
                    ),
                ),
                (
                    "date_arrive",
                    models.DateField(
                        blank=True, db_column="дата_прихода_на_склад", null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("США", "США"), ("ГЕРАМНИЯ", "ГЕРАМНИЯ")],
                        db_column="страна_склада",
                        max_length=100,
                    ),
                ),
                ("comments", models.TextField(db_column="коментарий")),
                ("rf_send", models.BooleanField(db_column="рф_отправленно")),
                (
                    "date_list_create",
                    models.DateField(verbose_name="дата_создания_листа"),
                ),
                (
                    "smart",
                    models.ForeignKey(
                        db_column="smart",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sellship.item",
                    ),
                ),
            ],
        ),
    ]
